### PR TITLE
XSS testing 

### PR DESCRIPTION
**Pull request by To-m-L**
# Description

Created a security report on the PwnXSS testing results on place_order

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

# Checklist:

- [x] My code follows the PEP 8 style guide for python
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by DouglasChafee — APPROVED** [review]
good analysis of the XSS threat in place_order

**Review by KarlDorogy — APPROVED** [review]
Nice analysis about the possible threat with our queries in the controller.

**Review by DouglasChafee — APPROVED** [review]
The SQL testing showed plenty of weaknesses in our qbay, good job explaining them.

**Review by KarlDorogy — APPROVED** [review]
👍

**Pull request merged**
